### ISSUE TITLE
Goals beyond/different from Kali?

### ISSUE THREAD

**Issue by jkrauska** [dataplane/dpdistro#1]
DIY feels like a lot of work here.

Do you have different requirements/needs that can't be met with something generic/security focused like Kali?

Best

**Comment by jtkdpu** [comment]
Hi Joel,

Yes it is potentially a lot of work.  It will be more like the DRG Distro, from which some of this work derives and more like monitors that RIPE deploys.  This platform is not a stand-alone pen testing distribution.  There isn't much here yet to make clear what it does, but it is intended to be a sensor system (primarily) that is widely deployed and centrally managed.
